//BRANDON SEIDMAN - 2020
//E115

//TWO SLASHES WILL MAKE A COMMENT IN YOUR CODE
/*
SLASH STAR THEN STAR SLASH
IS FOR MAKEING MULTILINE COMMENTS
*/
#include <iostream> //INCLUSIONS ARE PACKAGES NOT INCLUDED BY DEFAULT.
//PRETTY MUCH EVERY PROJECT YOU CREATE IN THIS CLASS WILL USE THE <iostream> INCLUSION
//<iostream> INCLUDES FUNCTIONS SUCH AS "cout" WHICH ALLOWS US TO OUTPUT TEXT TO CONSOLE

using namespace std; //std IS THE STANDARD NAMESPACE FOR C++
//WITHOUT THIS STATEMENT FUNCTIONS SUCH AS "cout" WOULD NEED TO BE WRITTEN AS "std::cout"
//THE SEMI-COLON AT THE END IS STANDARD IN C++ AND IS USED TO END ALL STATEMENTS

int main(){ //THIS IS A FUNCTION DECLARATION AND ITS MADE UP OF 4 PARTS
/*
PART 1: THE VARIABLE TYPE IS THE TYPE THAT THE FUNCTION RETURNS
        EVERY C++ PROGRAM HAS A MAIN FUNCTION THAT WILL BE DECLARED AS AN "int" FUNCTION
        WE WILL LEARN MORE ABOUT THE DIFFERENT TYPES OF VARIABLES LATER
*/
/*
PART 2: THE FUNCTION NAME, IN THIS CASE IT'S "main" BUT LATER YOU WILL BE MAKING YOUR OWN
        FUNCTIONS WITH YOUR OWN NAMES
*/
/*
PART 3: THE () BRACKETS ARE WHERE YOU PUT VARIABLES THAT YOU WANT TO INPUT IN YOUR FUNCTION
        FOR THE FIRST FEW PROJECTS THIS ISN'T IMPORTANT AND WILL JUST STAY EMPTY BUT LATER
        ON YOU WILL NEED TO SEND VARIABLES BETWEEN FUNCTIONS
*/
/*
PART 4: THE {} BRACKETS ARE WHERE YOU PUT YOUR CODE FOR THE FUNCTION
*/

  cout << "Hello World!" << endl; //THIS IS A STANDARD "cout" FUNCTION AND IT'S ALSO MADE UP OF A COUPLE PARTS
  // "cout" : THIS IS THE FUNCTION DECLARATION FOR "cout" WHICH IS USED TO PRINT INFORMATION TO THE CONSOLE
  // "<<" : THIS SEPERATES THE DIFFERENT PARTS OF THE "cout" STATEMENT AND SEPERATES PARTS THAT NEED TO BE PRINTED
  //        IF THEY ARE DIFFERENT TYPES (SUCH AS PRINTING AN INT THEN A STRING)
  // PRINT STATEMENT : THIS IS WHERE YOU TYPE WHAT YOU WANT TO PRINT. IF ITS A VARIABLE JUST TYPE THE VARIABLE
  //                   NAME BUT OTHERWISE TYPE WHATEVER YOU WANT TO PRINT IN QUOTES
  // "endl" : THIS IS AN ENDLINE STATEMENT WHICH IS ESSENTIALLY THE EQUIVELANT OF PRESSING "enter" or "return"

  return 0; //THIS IS A RETURN STATEMENT. IT SHOULD RETURN SOMETHING THAT IS OF THE SAME TYPE AS YOUR FUNCTION.
            //ITS PRETTY STANDARD IN MAIN FUNCTIONS TO JUST RETURN 0 OR 1

} //CLOSES THE MAIN FUNCTION
